<?php 
return [
	[
		'title'=>"Luxury Hotels",
		'hotels'=>[
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/grand-velas-riviera-nayarit-puerto-vallarta-1.jpg',
				'name'=>'Grand Velas Riviera Nayarit',
				'city'=>'Puerto Vallarta',
				'stars'=>5,
				'price'=>number_format(506.47,2),
				'link'=>'/hotels/puerto-vallarta/grand-velas-riviera-nayarit',
			],
			// [
			// 	'image'=>'https://www.goguytravel.com/storage/hotels/azul-beach-resort-negril-by-karisma-montego-bay.jpg',
			// 	'name'=>'Azul Beach Resort Negril by Karisma',
			// 	'city'=>'Montego Bay, Jamaica',
			// 	'stars'=>5,
			// 	'price'=>number_format(230.07,2),
			// 	'link'=>'/hotels/montego-bay/azul-beach-resort-negril-by-karisma',
			// ],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/allure-chocolat-by-karisma-cartagena.jpg',
				'name'=>'Allure Chocolat by Karisma',
				'city'=>'Cartagena, Colombia',
				'stars'=>5,
				'price'=>number_format(130.07,2),
				'link'=>'/hotels/cartagena/allure-chocolat-by-karisma',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/palafitos-overwater-bungalows-by-karisma-riviera-maya-20.jpg',
				'name'=>'Palafitos Overwater Bungalows By Karisma',
				'city'=>'Riviera maya',
				'stars'=>4,
				'price'=>number_format(1412.72,2),
				'link'=>'/hotels/riviera-maya/palafitos-overwater-bungalows-by-karisma',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/el-dorado-maroma-by-karisma-riviera-maya.jpg',
				'name'=>'El Dorado Maroma By Karisma',
				'city'=>'Riviera maya',
				'stars'=>4,
				'price'=>number_format(338.63,2),
				'link'=>'/hotels/riviera-maya/el-dorado-maroma-by-karisma',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/el-dorado-royale-by-karisma-riviera-maya.jpg',
				'name'=>'El Dorado Royale',
				'city'=>'Riviera maya',
				'stars'=>4,
				'price'=>number_format(296.60,2),
				'link'=>'/hotels/riviera-maya/el-dorado-royale-by-karisma',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/el-dorado-casitas-royale-by-karisma-riviera-maya-6.jpg',
				'name'=>'El Dorado Casitas Royale',
				'city'=>'Riviera maya',
				'stars'=>4,
				'price'=>number_format(380.66,2),
				'link'=>'/riviera-maya/el-dorado-casitas-royale-by-karisma',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/grand-velas-los-cabos-cabo-san-lucas-27.jpg',
				'name'=>'Grand Velas los Cabos',
				'city'=>'Los Cabos',
				'stars'=>5,
				'price'=>number_format(698.28,2),
				'link'=>'/hotels/cabo-san-lucas/grand-velas-los-cabos',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/grand-velas-riviera-maya-playa-del-carmen.jpg',
				'name'=>'Grand Velas Riviera Maya',
				'city'=>'Playa del Carmen',
				'stars'=>5,
				'price'=>number_format(528.83,2),
				'link'=>'/hotels/playa-del-carmen/grand-velas-riviera-maya',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/hyatt-zilara-cancun-cancun-0.Jpg',
				'name'=>'Hyatt Zilara Cancun',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(302.48,2),
				'link'=>'/hotels/cancun/hyatt-zilara-cancun',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/hyatt-ziva-cancun-cancun.Jpg',
				'name'=>'Hyatt Ziva Cancun',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(308.74,2),
				'link'=>'/hotels/cancun/hyatt-ziva-cancun',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/the-royal-playa-del-carmen-playa-del-carmen.jpg',
				'name'=>'THE Royal',
				'city'=>'Playa del carmen',
				'stars'=>5,
				'price'=>number_format(233.39,2),
				'link'=>'/hotels/playa-del-carmen/the-royal-playa-del-carmen',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/gran-caribe-resort-cancun-cancun.jpg',
				'name'=>'Gran Caribe Resort Cancún',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(194.79,2),
				'link'=>'/hotels/cancun/gran-caribe-resort-cancun',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/live-aqua-cancun-all-inclusive-adults-only-cancun.jpg',
				'name'=>'Live Aqua Cancun',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(294.59,2),
				'link'=>'/hotels/cancun/live-aqua-cancun-all-inclusive-adults-only',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/grand-fiesta-americana-coral-beach-cancun-cancun.jpg',
				'name'=>'Grand Fiesta Americana',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(183.22,2),
				'link'=>'/hotels/cancun/grand-fiesta-americana-coral-beach-cancun',
			],
		]
	],
	[
		'title'=>"Top Ten Best Deals for Cancun and Riviera Maya",
		'hotels'=>[
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/golden-parnassus-all-inclusive-resort-spa-adults-only-cancun-5.jpg',
				'name'=>'Golden Parnassus',
				'city'=>'Cancun',
				'stars'=>4,
				'price'=>number_format(138.31,2),
				'link'=>'/hotels/cancun/golden-parnassus-all-inclusive-resort-spa-adults-only',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/gr-caribe-by-solaris-cancun-0.jpg',
				'name'=>'GR Caribe by Solaris',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(208.84,2),
				'link'=>'/hotels/cancun/gr-caribe-by-solaris',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/park-royal-cancun-cancun.jpg',
				'name'=>'Park Royal Cancun',
				'city'=>'Cancun',
				'stars'=>4,
				'price'=>number_format(136.85,2),
				'link'=>'/hotels/cancun/park-royal-cancun',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/cancun-bay-resort-cancun-19.JPG',
				'name'=>'Cancun Bay Resort',
				'city'=>'Cancun',
				'stars'=>4,
				'price'=>number_format(108.52,2),
				'link'=>'/hotels/cancun/cancun-bay-resort',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/seadust-cancun-family-resort-cancun-61.jpg',
				'name'=>'Seadust Cancun Resort',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(175.00,2),
				'link'=>'/hotels/cancun/seadust-cancun-family-resort',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/flamingo-cancun-resort-cancun.jpg',
				'name'=>'Flamingo Cancun Resort',
				'city'=>'Cancun',
				'stars'=>4,
				'price'=>number_format(88.00,2),
				'link'=>'/hotels/cancun/flamingo-cancun-resort',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/omni-cancun-hotel-villas-cancun.jpg',
				'name'=>'Omni Cancun Hotel & Villas',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(212.88,2),
				'link'=>'/hotels/cancun/omni-cancun-hotel-villas',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/the-reef-coco-beach-playa-del-carmen.jpg ',
				'name'=>'The Reef Coco Beach',
				'city'=>'Cancun',
				'stars'=>4,
				'price'=>number_format(105.07,2),
				'link'=>'/hotels/playa-del-carmen/the-reef-coco-beach',
			],
		]
	],
	[
		'title'=>"Top Ten Best Deals for Cancun and Riviera Maya",
		'hotels'=>[
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/seadust-cancun-family-resort-cancun-58.jpg',
				'name'=>'Seadust Cancun Resort',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(175.00,2),
				'link'=>'/hotels/cancun/seadust-cancun-family-resort',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/flamingo-cancun-resort-cancun.jpg',
				'name'=>'Flamingo Cancun Resort',
				'city'=>'Cancun',
				'stars'=>4,
				'price'=>number_format(88.00,2),
				'link'=>'/hotels/cancun/flamingo-cancun-resort',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/park-royal-cancun-cancun.jpg',
				'name'=>'Park Royal Cancun',
				'city'=>'Cancun',
				'stars'=>4,
				'price'=>number_format(120.69,2),
				'link'=>'/hotels/cancun/park-royal-cancun',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/gr-caribe-by-solaris-cancun-1.jpg',
				'name'=>'GR Caribe by Solaris',
				'city'=>'Cancun',
				'stars'=>5,
				'price'=>number_format(175.86,2),
				'link'=>'/hotels/cancun/gr-caribe-by-solaris',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/the-reef-coco-beach-playa-del-carmen.jpg',
				'name'=>'The Reef Coco Beach',
				'city'=>'Playa del carmen',
				'stars'=>4,
				'price'=>number_format(105.07,2),
				'link'=>'/hotels/playa-del-carmen/the-reef-coco-beach',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/the-reef-playacar-resort-and-spa-playa-del-carmen.jpg',
				'name'=>'The Reef Playacar',
				'city'=>'Playa del carmen',
				'stars'=>4,
				'price'=>number_format(113.15,2),
				'link'=>'/hotels/playa-del-carmen/the-reef-playacar-resort-and-spa',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/the-royal-playa-del-carmen-playa-del-carmen.jpg',
				'name'=>'THE Royal',
				'city'=>'Playa del carmen',
				'stars'=>5,
				'price'=>number_format(191.29,2),
				'link'=>'/hotels/playa-del-carmen/the-royal-playa-del-carmen',
			],
			[
				'image'=>'https://www.goguytravel.com/storage/hotels/grand-velas-riviera-maya-playa-del-carmen-3.jpg',
				'name'=>'Grand Velas Riviera Maya',
				'city'=>'Playa del carmen',
				'stars'=>5,
				'price'=>number_format(528.83,2),
				'link'=>'/hotels/playa-del-carmen/grand-velas-riviera-maya',
			],
		]
	]
];
 ?>